### ISSUE TITLE
Site Improve - User Feedback Feature  (from 2024)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-other#2]
**Problem Description:**
Site Improve has a user feedback feature available to use. This feature will allow us to create a survey, containing one question, which can then be displayed on a specific URL page of our choosing. 

**Expected Behavior/Solution:**
The Feedback Survey shows on the desired URL, with our desired layout and rating system and we are able to track and receive this feedback from Site Improve/Email notifications. 

**Requirements:**
- Feedback Survey appears in all URL's which contain the snippet of `https://lux-front-tst.collections.yale.edu/view/`
- Feedback Survey has the desired question displayed: `How was your experience using LUX?`
- Feedback survey is displayed in the middle on the right hand side
- Feedback Survey displays a smiling rating style.
- Feedback survey requires a rating and has its comment box set to optional. 
- External link redirects user to the User Testing survey. 
- The submission of a survey or the selection of `don't show this again` will prompt the survey to disappear for the remainder of the user session. 
- Metrics will be added to the Heart Framework Dashboard.  

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Heather~~
- [x] Setting up Feedback Survey - Amy 
- [x] Testing survey in LUX-TST - Amy 
- [ ] Committee discussions - Sarah
- [ ] Feasibility/Team discussion - Sarah
- [ ] ~Backend requirements - TBD (might need depending on what Zach says)~ 
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**
- https://lux-front-tst.collections.yale.edu/view/results/objects?q=%7B%22AND%22%3A%5B%7B%22text%22%3A%22andy%22%2C%22_lang%22%3A%22en%22%7D%2C%7B%22text%22%3A%22warhol%22%2C%22_lang%22%3A%22en%22%7D%5D%7D&sq=andy+warhol 
- Site Improve Dashboard: [Heart Framework
](https://my2.siteimprove.com/Dashboard/37221619454/35972541307/Today/Dashboard/Index)

**Dependencies/Blocks:**
- ~Blocked By: Sylvia's LUX Assessment plan (in development)~
- [Site Improve Support Ticket](https://help.siteimprove.com/support/tickets/2701270)

**Related Github Issues:**
N/A

**Related links:**
- [Steps to creating a user feedback survey](https://help.siteimprove.com/support/solutions/articles/80000863902-how-to-create-a-feedback-survey-in-analytics)
- [Prioritizing feedback ](https://help.siteimprove.com/support/solutions/articles/80001098864-how-to-prioritize-the-feedback-you-are-most-interested-in-siteimprove-feedback-)
- https://my2.siteimprove.com/Settings/359298/AnalyticsFeedback/Index

**Wireframe/Mockup:**
Current: 
![image](https://github.com/user-attachments/assets/eb539f44-7905-44ca-846f-4b66c979145c)

Expected: 
![image](https://github.com/user-attachments/assets/8f46ade2-ff03-4c5b-b909-f99cd7a2caab)

**Comment by roamye** [comment]
From UX/BA 9/25: 
This was approved by the team in TST. 
Sarah T will update the survey  link to keep the LUX checkbox hidden as this survey link will only be accessible to those coming from the LUX site. However this will not affect the survey as the link will remain the same. 

Next steps: UAT reviewal

**Comment by roamye** [comment]
This was approved by UAT on sept 27. Closing as it is now in production and working fine.
