### ISSUE TITLE
Provide convenient means to override select search options, from the simple search context (from 902)

### ISSUE THREAD

**Issue by gigamorph** [project-lux/lux-other#3]
**Problem Description:**
_Excerpts from [this Teams conversation](https://teams.microsoft.com/l/message/19:GmLeQu1cBR40mfrno-l8lngg7RFCcJs8fvFIw-MJjIM1@thread.tacv2/1681589421887?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=4620eac6-0955-4c69-93e8-b493b21f0df6&parentMessageId=1681589421887&teamName=MarkLogic&channelName=General&createdTime=1681589421887&allowXTenantAccess=false) follow._

> SP: **Use case:** find all LUX records that mention the novel The Bluest Eye with a keyword search for "the bluest eye"
> 
> SP: Current functionality kind of stinks for this: Keyword search stems and wildcards a quoted search, so that is basically useless here in a book with such common words.   I can use advanced search/exact match, but I would have to redo to the search for each entity type. 
> 
> RS: Except for every time you want it to be exact, there's at least 10 times you want it to do stemming
> 
> _[Examples of when you would not want exact]_
> 
> SP: Agree on those, but it's frustrating:  there's no way to get these kind of results in simple search.   Can't add morrison because she's not in the object records.

There are ways that we could support overriding individual or a set of search options, such as:

1. The MarkLogic grammar's term-level search options syntax, such as `"blue eyes" [unstemmed]`
2. Utilizing the MarkLogic grammar's bound tags feature, such as `exact:"blue eyes"`
3. Using an uncommon set of characters instead of quotes, such as `[blue eyes]` or `<blue eyes>`

If the choice we make does not specify multiple options but must override multiple options, we'll need to define what those are.

We need to ensure that the same results are returned upon switching from simple search to advanced search.  We may not have to support going from advanced to simple search.

**Expected Behavior/Solution:**
TBD

**Requirements:**
TBD

**Needed for promotion:**
If an item on the list is not needed, it should be crossed off but not removed.

~~- [ ] Wireframe/Mockup - Heather~~
~~- [ ] Committee discussions - Sarah~~
- [ ] Feasibility/Team discussion - Sarah
- [ ] Backend requirements - TBD
- [ ] Frontend requirements- TBD
- [ ] Questions
- List of questions for discussions. Answers should be documented within the issue.

**UAT/LUX Examples:**

**Dependencies/Blocks:**

**Related Github Issues:**

- https://git.yale.edu/lux-its/marklogic/issues/521 (but for a single word) 
- https://git.yale.edu/lux-its/marklogic/issues/585 (stop words) 
- https://git.yale.edu/lux-its/marklogic/issues/810 (but for advanced search) 
- https://git.yale.edu/lux-its/marklogic/issues/855 (but for advanced search) 

**Related links:**

**Comment by roamye** [comment]
@clarkepeterf - do we know how to implement this ticket? or should this be a research ticket instead?

**Comment by clarkepeterf** [comment]
@roamye this ticket needs more forming from a user-perspective. What is the desired syntax to get an exact search from simple search?

@prowns / @azaroth42  / others need to determine what the desired functionality is based on [this Teams conversation](https://teams.microsoft.com/l/message/19:GmLeQu1cBR40mfrno-l8lngg7RFCcJs8fvFIw-MJjIM1@thread.tacv2/1681589421887?tenantId=dd8cbebb-2139-4df8-b411-4e3e87abeb5c&groupId=4620eac6-0955-4c69-93e8-b493b21f0df6&parentMessageId=1681589421887&teamName=MarkLogic&channelName=General&createdTime=1681589421887&allowXTenantAccess=false)

Once the desired functionality is known, I can work on implementing it.

**Comment by azaroth42** [comment]
I remain :-1: on the issue

**Comment by prowns** [comment]
@roamye - recommendation - update Help Text to note that "quoted searches" are stemmed and wildcarded by default. Users need to switch to advanced search and turn off Stemmed/Wildcard options in the gear for more precise control. ooa

**Comment by roamye** [comment]
Updated help text with @prowns.
