### ISSUE TITLE
Research: Icon placement in advanced search

### ISSUE THREAD

**Issue by roamye** [project-lux/lux-other#6]
**Problem Description** 
UX/UI research is needed to determine which layout option decreases user confusion. 

**Expected Behavior/Solution**
A/B testing will need to be conducted to determine the best mockup to implement. 

**Requirements** 
- Once A/B testing is complete, the favored mockup will be added to the FE issue.

**Needed for Promotion**

- [ ] Wireframe/mockup - Mike
- [ ] A/B testing - Sylvia 
- [ ] Feasibility/Team discussion - Sarah
- [X] Frontend Support 
- [ ] Questions
- Should there be a show less button at the top? 

**Dependencies/Blocks:**
- Blocking implementation: https://github.com/project-lux/lux-frontend/issues/338 

**Related Github Issues:**
NA

**Related Links**
https://docs.google.com/document/d/1aJi5fN4y3e9V1v7rRFWypbLmBlHWkTDh6siwPoTqKDc/edit?tab=t.0

**Wireframe/Mockups**
Current: 

Desired 1: 

Desired 2:

**Comment by prowns** [comment]
@roamye  - can this be closed? discussed at interactions.

**Comment by roamye** [comment]
@prowns - if we no longer need to conduct testing on the mockups @miketullo95 is working on then yes.

**Comment by roamye** [comment]
Closing as mike does not need to conduct testing.
